# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_netcdfbrowser.ui'
#
# Created: Wed Jan 30 16:17:30 2013
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_NetCDFBrowser(object):
    def setupUi(self, NetCDFBrowser):
        NetCDFBrowser.setObjectName(_fromUtf8("NetCDFBrowser"))
        NetCDFBrowser.resize(424, 330)
        self.gridLayout = QtGui.QGridLayout(NetCDFBrowser)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label = QtGui.QLabel(NetCDFBrowser)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_3 = QtGui.QLabel(NetCDFBrowser)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.label_4 = QtGui.QLabel(NetCDFBrowser)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 6, 0, 1, 1)
        self.line_2 = QtGui.QFrame(NetCDFBrowser)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridLayout.addWidget(self.line_2, 8, 0, 1, 2)
        self.leURI = QtGui.QLineEdit(NetCDFBrowser)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leURI.sizePolicy().hasHeightForWidth())
        self.leURI.setSizePolicy(sizePolicy)
        self.leURI.setReadOnly(True)
        self.leURI.setObjectName(_fromUtf8("leURI"))
        self.gridLayout.addWidget(self.leURI, 6, 1, 1, 1)
        self.cboVars = QtGui.QComboBox(NetCDFBrowser)
        self.cboVars.setObjectName(_fromUtf8("cboVars"))
        self.gridLayout.addWidget(self.cboVars, 1, 1, 1, 1)
        self.label_2 = QtGui.QLabel(NetCDFBrowser)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.line_3 = QtGui.QFrame(NetCDFBrowser)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.gridLayout.addWidget(self.line_3, 2, 0, 1, 2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.leFileName = QtGui.QLineEdit(NetCDFBrowser)
        self.leFileName.setObjectName(_fromUtf8("leFileName"))
        self.horizontalLayout.addWidget(self.leFileName)
        self.pbnFileName = QtGui.QToolButton(NetCDFBrowser)
        self.pbnFileName.setObjectName(_fromUtf8("pbnFileName"))
        self.horizontalLayout.addWidget(self.pbnFileName)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 1, 1, 1)
        self.gridGroupBox = QtGui.QGroupBox(NetCDFBrowser)
        self.gridGroupBox.setObjectName(_fromUtf8("gridGroupBox"))
        self.gridLayout_2 = QtGui.QGridLayout(self.gridGroupBox)
        self.gridLayout_2.setContentsMargins(-1, -1, -1, 0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.lblDim1 = QtGui.QLabel(self.gridGroupBox)
        self.lblDim1.setObjectName(_fromUtf8("lblDim1"))
        self.gridLayout_2.addWidget(self.lblDim1, 0, 0, 1, 1)
        self.lblDim2 = QtGui.QLabel(self.gridGroupBox)
        self.lblDim2.setObjectName(_fromUtf8("lblDim2"))
        self.gridLayout_2.addWidget(self.lblDim2, 1, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.cboDim1 = QtGui.QComboBox(self.gridGroupBox)
        self.cboDim1.setObjectName(_fromUtf8("cboDim1"))
        self.horizontalLayout_3.addWidget(self.cboDim1)
        self.pbnDim1 = QtGui.QPushButton(self.gridGroupBox)
        self.pbnDim1.setObjectName(_fromUtf8("pbnDim1"))
        self.horizontalLayout_3.addWidget(self.pbnDim1)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 0, 1, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.cboDim2 = QtGui.QComboBox(self.gridGroupBox)
        self.cboDim2.setObjectName(_fromUtf8("cboDim2"))
        self.horizontalLayout_5.addWidget(self.cboDim2)
        self.pbnDim2 = QtGui.QPushButton(self.gridGroupBox)
        self.pbnDim2.setObjectName(_fromUtf8("pbnDim2"))
        self.horizontalLayout_5.addWidget(self.pbnDim2)
        self.gridLayout_2.addLayout(self.horizontalLayout_5, 1, 1, 1, 1)
        self.cbxMultiSelection = QtGui.QCheckBox(self.gridGroupBox)
        self.cbxMultiSelection.setChecked(True)
        self.cbxMultiSelection.setObjectName(_fromUtf8("cbxMultiSelection"))
        self.gridLayout_2.addWidget(self.cbxMultiSelection, 2, 0, 1, 1)
        self.pbnAddSelection = QtGui.QPushButton(self.gridGroupBox)
        self.pbnAddSelection.setObjectName(_fromUtf8("pbnAddSelection"))
        self.gridLayout_2.addWidget(self.pbnAddSelection, 2, 1, 1, 1)
        self.gridLayout.addWidget(self.gridGroupBox, 3, 1, 1, 1)
        self.leBandSelection = QtGui.QLineEdit(NetCDFBrowser)
        self.leBandSelection.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leBandSelection.sizePolicy().hasHeightForWidth())
        self.leBandSelection.setSizePolicy(sizePolicy)
        self.leBandSelection.setReadOnly(True)
        self.leBandSelection.setObjectName(_fromUtf8("leBandSelection"))
        self.gridLayout.addWidget(self.leBandSelection, 5, 1, 1, 1)
        self.line_4 = QtGui.QFrame(NetCDFBrowser)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.gridLayout.addWidget(self.line_4, 4, 0, 1, 2)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.gridLayout.addLayout(self.horizontalLayout_4, 7, 1, 1, 1)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_6 = QtGui.QLabel(NetCDFBrowser)
        self.label_6.setEnabled(False)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_6.addWidget(self.label_6)
        self.cboRenderer = QtGui.QComboBox(NetCDFBrowser)
        self.cboRenderer.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboRenderer.sizePolicy().hasHeightForWidth())
        self.cboRenderer.setSizePolicy(sizePolicy)
        self.cboRenderer.setObjectName(_fromUtf8("cboRenderer"))
        self.cboRenderer.addItem(_fromUtf8(""))
        self.cboRenderer.addItem(_fromUtf8(""))
        self.horizontalLayout_6.addWidget(self.cboRenderer)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.buttonBox = QtGui.QDialogButtonBox(NetCDFBrowser)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Close)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.horizontalLayout_6.addWidget(self.buttonBox)
        self.gridLayout.addLayout(self.horizontalLayout_6, 9, 0, 1, 2)
        self.label_7 = QtGui.QLabel(NetCDFBrowser)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 5, 0, 1, 1)

        self.retranslateUi(NetCDFBrowser)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), NetCDFBrowser.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), NetCDFBrowser.reject)
        QtCore.QMetaObject.connectSlotsByName(NetCDFBrowser)

    def retranslateUi(self, NetCDFBrowser):
        NetCDFBrowser.setWindowTitle(QtGui.QApplication.translate("NetCDFBrowser", "NetCDFBrowser", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("NetCDFBrowser", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("NetCDFBrowser", "Dimensions", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("NetCDFBrowser", "URI", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("NetCDFBrowser", "Variable", None, QtGui.QApplication.UnicodeUTF8))
        self.pbnFileName.setText(QtGui.QApplication.translate("NetCDFBrowser", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.lblDim1.setText(QtGui.QApplication.translate("NetCDFBrowser", "     -     ", None, QtGui.QApplication.UnicodeUTF8))
        self.lblDim2.setText(QtGui.QApplication.translate("NetCDFBrowser", "     -     ", None, QtGui.QApplication.UnicodeUTF8))
        self.pbnDim1.setText(QtGui.QApplication.translate("NetCDFBrowser", "Select", None, QtGui.QApplication.UnicodeUTF8))
        self.pbnDim2.setText(QtGui.QApplication.translate("NetCDFBrowser", "Select", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxMultiSelection.setText(QtGui.QApplication.translate("NetCDFBrowser", "multi-selection", None, QtGui.QApplication.UnicodeUTF8))
        self.pbnAddSelection.setText(QtGui.QApplication.translate("NetCDFBrowser", "Add selection", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("NetCDFBrowser", "Renderer", None, QtGui.QApplication.UnicodeUTF8))
        self.cboRenderer.setItemText(0, QtGui.QApplication.translate("NetCDFBrowser", "gray", None, QtGui.QApplication.UnicodeUTF8))
        self.cboRenderer.setItemText(1, QtGui.QApplication.translate("NetCDFBrowser", "pseudo", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("NetCDFBrowser", "Selected bands", None, QtGui.QApplication.UnicodeUTF8))

