# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_netcdfbrowser.ui'
#
# Created: Fri Mar  7 15:54:16 2014
#      by: PyQt4 UI code generator 4.10
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_NetCDFBrowser(object):
    def setupUi(self, NetCDFBrowser):
        NetCDFBrowser.setObjectName(_fromUtf8("NetCDFBrowser"))
        NetCDFBrowser.resize(474, 303)
        self.gridLayout = QtGui.QGridLayout(NetCDFBrowser)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_4 = QtGui.QLabel(NetCDFBrowser)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 10, 0, 1, 1)
        self.label_5 = QtGui.QLabel(NetCDFBrowser)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(0, 0))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.leFileName = QtGui.QLineEdit(NetCDFBrowser)
        self.leFileName.setObjectName(_fromUtf8("leFileName"))
        self.gridLayout.addWidget(self.leFileName, 0, 1, 1, 1)
        self.label = QtGui.QLabel(NetCDFBrowser)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_7 = QtGui.QLabel(NetCDFBrowser)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 9, 0, 1, 1)
        self.label_2 = QtGui.QLabel(NetCDFBrowser)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 1)
        self.label_3 = QtGui.QLabel(NetCDFBrowser)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 5, 0, 2, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.lblDim1 = QtGui.QLabel(NetCDFBrowser)
        self.lblDim1.setObjectName(_fromUtf8("lblDim1"))
        self.horizontalLayout.addWidget(self.lblDim1)
        self.pbnDim1 = QtGui.QPushButton(NetCDFBrowser)
        self.pbnDim1.setObjectName(_fromUtf8("pbnDim1"))
        self.horizontalLayout.addWidget(self.pbnDim1)
        self.gridLayout.addLayout(self.horizontalLayout, 5, 1, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.lblDim2 = QtGui.QLabel(NetCDFBrowser)
        self.lblDim2.setObjectName(_fromUtf8("lblDim2"))
        self.horizontalLayout_2.addWidget(self.lblDim2)
        self.pbnDim2 = QtGui.QPushButton(NetCDFBrowser)
        self.pbnDim2.setObjectName(_fromUtf8("pbnDim2"))
        self.horizontalLayout_2.addWidget(self.pbnDim2)
        self.gridLayout.addLayout(self.horizontalLayout_2, 6, 1, 1, 1)
        self.cboCrs = QtGui.QComboBox(NetCDFBrowser)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboCrs.sizePolicy().hasHeightForWidth())
        self.cboCrs.setSizePolicy(sizePolicy)
        self.cboCrs.setMinimumSize(QtCore.QSize(250, 0))
        self.cboCrs.setObjectName(_fromUtf8("cboCrs"))
        self.gridLayout.addWidget(self.cboCrs, 2, 1, 1, 1)
        self.pbnFileName = QtGui.QPushButton(NetCDFBrowser)
        self.pbnFileName.setObjectName(_fromUtf8("pbnFileName"))
        self.gridLayout.addWidget(self.pbnFileName, 0, 2, 1, 1)
        self.leURI = QtGui.QLineEdit(NetCDFBrowser)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leURI.sizePolicy().hasHeightForWidth())
        self.leURI.setSizePolicy(sizePolicy)
        self.leURI.setReadOnly(True)
        self.leURI.setObjectName(_fromUtf8("leURI"))
        self.gridLayout.addWidget(self.leURI, 10, 1, 1, 1)
        self.cboVars = QtGui.QComboBox(NetCDFBrowser)
        self.cboVars.setObjectName(_fromUtf8("cboVars"))
        self.gridLayout.addWidget(self.cboVars, 3, 1, 1, 1)
        self.pbnAddSelection = QtGui.QPushButton(NetCDFBrowser)
        self.pbnAddSelection.setObjectName(_fromUtf8("pbnAddSelection"))
        self.gridLayout.addWidget(self.pbnAddSelection, 5, 2, 2, 1)
        self.leBandSelection = QtGui.QLineEdit(NetCDFBrowser)
        self.leBandSelection.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leBandSelection.sizePolicy().hasHeightForWidth())
        self.leBandSelection.setSizePolicy(sizePolicy)
        self.leBandSelection.setReadOnly(True)
        self.leBandSelection.setObjectName(_fromUtf8("leBandSelection"))
        self.gridLayout.addWidget(self.leBandSelection, 9, 1, 1, 1)
        self.pbnCrs = QtGui.QPushButton(NetCDFBrowser)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbnCrs.sizePolicy().hasHeightForWidth())
        self.pbnCrs.setSizePolicy(sizePolicy)
        self.pbnCrs.setObjectName(_fromUtf8("pbnCrs"))
        self.gridLayout.addWidget(self.pbnCrs, 2, 2, 1, 1)
        self.line = QtGui.QFrame(NetCDFBrowser)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout.addWidget(self.line, 4, 0, 1, 3)
        self.line_4 = QtGui.QFrame(NetCDFBrowser)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.gridLayout.addWidget(self.line_4, 8, 0, 1, 3)
        self.line_2 = QtGui.QFrame(NetCDFBrowser)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridLayout.addWidget(self.line_2, 12, 0, 1, 3)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_6 = QtGui.QLabel(NetCDFBrowser)
        self.label_6.setEnabled(False)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_6.addWidget(self.label_6)
        self.cboRenderer = QtGui.QComboBox(NetCDFBrowser)
        self.cboRenderer.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboRenderer.sizePolicy().hasHeightForWidth())
        self.cboRenderer.setSizePolicy(sizePolicy)
        self.cboRenderer.setObjectName(_fromUtf8("cboRenderer"))
        self.cboRenderer.addItem(_fromUtf8(""))
        self.cboRenderer.addItem(_fromUtf8(""))
        self.horizontalLayout_6.addWidget(self.cboRenderer)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.buttonBox = QtGui.QDialogButtonBox(NetCDFBrowser)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Close)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.horizontalLayout_6.addWidget(self.buttonBox)
        self.gridLayout.addLayout(self.horizontalLayout_6, 13, 0, 1, 3)

        self.retranslateUi(NetCDFBrowser)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), NetCDFBrowser.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), NetCDFBrowser.reject)
        QtCore.QMetaObject.connectSlotsByName(NetCDFBrowser)

    def retranslateUi(self, NetCDFBrowser):
        NetCDFBrowser.setWindowTitle(_translate("NetCDFBrowser", "NetCDFBrowser", None))
        self.label_4.setText(_translate("NetCDFBrowser", "URI", None))
        self.label_5.setText(_translate("NetCDFBrowser", "CRS", None))
        self.label.setText(_translate("NetCDFBrowser", "File", None))
        self.label_7.setText(_translate("NetCDFBrowser", "Selected bands", None))
        self.label_2.setText(_translate("NetCDFBrowser", "Variable", None))
        self.label_3.setText(_translate("NetCDFBrowser", "Dimensions", None))
        self.lblDim1.setText(_translate("NetCDFBrowser", "     -     ", None))
        self.pbnDim1.setText(_translate("NetCDFBrowser", "Select", None))
        self.lblDim2.setText(_translate("NetCDFBrowser", "     -     ", None))
        self.pbnDim2.setText(_translate("NetCDFBrowser", "Select", None))
        self.pbnFileName.setText(_translate("NetCDFBrowser", "Load ...", None))
        self.pbnAddSelection.setText(_translate("NetCDFBrowser", "Add selection", None))
        self.pbnCrs.setText(_translate("NetCDFBrowser", "Change ...", None))
        self.label_6.setText(_translate("NetCDFBrowser", "Renderer", None))
        self.cboRenderer.setItemText(0, _translate("NetCDFBrowser", "gray", None))
        self.cboRenderer.setItemText(1, _translate("NetCDFBrowser", "pseudo", None))

